import pandas as pd

# Load conflict data generated by pass script
df = pd.read_csv('plotconflicts.csv')
df['overlap_start'] = pd.to_datetime(df['overlap_start'])
df['duration_min'] = df['duration_sec'] / 60.0
df['hour_utc'] = df['overlap_start'].dt.hour

# Normalize satellite pairing order for consistent grouping
df['sat_pair'] = df.apply(
    lambda r: f"{min(r['sat_a'], r['sat_b'])} <-> {max(r['sat_a'], r['sat_b'])}", axis=1
)

for station, group in df.groupby('station'):
    print("=" * 75)
    print(f" GROUND STATION SUMMARY REPORT: {station.upper()} ".center(75, "="))
    print("=" * 75)
    
    # --- 1. PAIRWISE CONTENTION TOTALS ---
    print("\n--- 1. PAIRWISE CONTENTION SUMMARY (7-DAY TOTAL) ---")
    pairwise = group.groupby('sat_pair').agg(
        conflict_count=('duration_min', 'count'),
        total_minutes=('duration_min', 'sum')
    ).reset_index().sort_values(by='total_minutes', ascending=False)
    
    print(f"{'Satellite Pair':<45} | {'Events':<7} | {'Total Duration'}")
    print("-" * 75)
    for _, r in pairwise.iterrows():
        print(f"{r['sat_pair']:<45} | {r['conflict_count']:<7} | {r['total_minutes']:>6.1f} mins")
    
    print("-" * 75)
    print(f"{'STATION TOTAL':<45} | {len(group):<7} | {group['duration_min'].sum():>6.1f} mins")

    # --- 2. HOURLY RUSH HOUR DISTRIBUTION ---
    print("\n--- 2. HOURLY RUSH HOUR DISTRIBUTION (UTC) ---")
    hourly = group['hour_utc'].value_counts().reindex(range(24), fill_value=0)
    
    print(f"{'UTC Hour':<10} | {'Conflicts':<10} | {'Peak Volume'}")
    print("-" * 45)
    for hour in range(24):
        count = hourly[hour]
        bar = "█" * count if count > 0 else "-"
        print(f"{hour:02d}:00 UTC   | {count:<10} | {bar}")
    print("\n")

import pandas as pd

def print_station_analytics(df_passes, df_conflicts):
    df_passes['aos'] = pd.to_datetime(df_passes['aos'])
    df_passes['los'] = pd.to_datetime(df_passes['los'])

    if not df_conflicts.empty:
        df_conflicts['overlap_start'] = pd.to_datetime(df_conflicts['overlap_start'])
        df_conflicts['overlap_end'] = pd.to_datetime(df_conflicts['overlap_end'])
        df_conflicts['duration_min'] = df_conflicts['duration_sec'] / 60.0
        df_conflicts['hour_utc'] = df_conflicts['overlap_start'].dt.hour
        df_conflicts['sat_pair'] = df_conflicts.apply(
            lambda r: f"{min(r['sat_a'], r['sat_b'])} <-> {max(r['sat_a'], r['sat_b'])}", axis=1
        )

    for station, st_passes in df_passes.groupby('station'):
        st_conflicts = df_conflicts[df_conflicts['station'] == station] if not df_conflicts.empty else pd.DataFrame()

        # --- TIME SWEEP FOR CONCURRENCY & BUSY TIME ---
        events = []
        for _, row in st_passes.iterrows():
            events.append((row['aos'], +1, row['sat']))
            events.append((row['los'], -1, row['sat']))
        events.sort(key=lambda x: x[0])

        active_sats = set()
        prev_time = None
        concurrency_durations = {1: 0.0, 2: 0.0, 3: 0.0} # 1 sat, 2 sat, 3+ sat minutes
        peak_concurrency = 0
        peak_sats_involved = set()

        for time, event_type, sat in events:
            if prev_time is not None and time > prev_time:
                dur_min = (time - prev_time).total_seconds() / 60.0
                count = len(active_sats)
                if count >= 1:
                    bucket = min(count, 3)
                    concurrency_durations[bucket] += dur_min
                if count > peak_concurrency:
                    peak_concurrency = count
                    peak_sats_involved = set(active_sats)

            if event_type == +1:
                active_sats.add(sat)
            else:
                active_sats.discard(sat)
            prev_time = time

        total_tracking_min = sum(concurrency_durations.values())
        total_7day_min = 7 * 24 * 60
        utilization_pct = (total_tracking_min / total_7day_min) * 100

        # Pass impact classification
        conflicted_sat_names = set(st_conflicts['sat_a']).union(set(st_conflicts['sat_b'])) if not st_conflicts.empty else set()

        print("=" * 80)
        print(f" OPERATIONAL ANALYTICS REPORT: {station.upper()} ".center(80, "="))
        print("=" * 80)

        # --- EXECUTIVE HIGH-LEVEL METRICS ---
        print("\n[ EXECUTIVE OVERVIEW ]")
        print(f"  * Total Planned Passes       : {len(st_passes)}")
        print(f"  * Station Utilization Rate   : {utilization_pct:.1f}% ({total_tracking_min:.1f} mins active / 10,080 mins)")
        print(f"  * Uncontended (Clear) Time   : {concurrency_durations[1]:.1f} mins ({concurrency_durations[1]/max(total_tracking_min,1)*100:.1f}% of active time)")
        print(f"  * Contended Overlap Time     : {(concurrency_durations[2] + concurrency_durations[3]):.1f} mins")
        print(f"  * Peak Concurrency           : {peak_concurrency} Satellites Simultaneously Overhead")
        print(f"  * 3+ Satellite Bottlenecks   : {concurrency_durations[3]:.1f} mins total duration")

        # --- PER-SATELLITE IMPACT RANKING ---
        print("\n[ SATELLITE IMPACT BREAKDOWN ]")
        sat_stats = []
        for sat in st_passes['sat'].unique():
            sat_p = st_passes[st_passes['sat'] == sat]
            sat_c = st_conflicts[(st_conflicts['sat_a'] == sat) | (st_conflicts['sat_b'] == sat)] if not st_conflicts.empty else pd.DataFrame()

            total_p = len(sat_p)
            conflict_p_cnt = len(sat_c)
            conflict_mins = sat_c['duration_min'].sum() if not sat_c.empty else 0.0

            sat_stats.append({
                'sat': sat,
                'passes': total_p,
                'conflicts': conflict_p_cnt,
                'conflict_mins': conflict_mins,
                'impact_pct': (conflict_p_cnt / total_p * 100) if total_p > 0 else 0
            })

        df_sat_stats = pd.DataFrame(sat_stats).sort_values('conflict_mins', ascending=False)
        print(f"  {'Satellite Name':<28} | {'Passes':<7} | {'Conflicted':<10} | {'Contention Time':<15} | {'Impact %'}")
        print("  " + "-" * 76)
        for _, r in df_sat_stats.iterrows():
            print(f"  {r['sat']:<28} | {r['passes']:<7} | {r['conflicts']:<10} | {r['conflict_mins']:>6.1f} mins     | {r['impact_pct']:>5.1f}%")

        # --- WORST SINGLE CONFLICT EVENT ---
        if not st_conflicts.empty:
            worst_evt = st_conflicts.loc[st_conflicts['duration_min'].idxmax()]
            print("\n[ LONGEST SINGLE CONFLICT EVENT ]")
            print(f"  * Pair     : {worst_evt['sat_a']} vs {worst_evt['sat_b']}")
            print(f"  * Start    : {worst_evt['overlap_start'].strftime('%Y-%m-%d %H:%M:%S UTC')}")
            print(f"  * End      : {worst_evt['overlap_end'].strftime('%Y-%m-%d %H:%M:%S UTC')}")
            print(f"  * Duration : {worst_evt['duration_min']:.1f} minutes")

        # --- PAIRWISE OVERLAP MATRIX ---
        if not st_conflicts.empty:
            print("\n[ TOP PAIRWISE CONTENTION TOTALS ]")
            pairwise = st_conflicts.groupby('sat_pair').agg(
                conflict_count=('duration_min', 'count'),
                total_minutes=('duration_min', 'sum')
            ).reset_index().sort_values(by='total_minutes', ascending=False)

            print(f"  {'Satellite Pair':<45} | {'Events':<7} | {'Total Duration'}")
            print("  " + "-" * 72)
            for _, r in pairwise.head(8).iterrows():  # Top 8 pairings
                print(f"  {r['sat_pair']:<45} | {r['conflict_count']:<7} | {r['total_minutes']:>6.1f} mins")

        # --- HOURLY RUSH HOUR DISTRIBUTION ---
        if not st_conflicts.empty:
            print("\n[ HOURLY CONFLICT DISTRIBUTION (UTC) ]")
            hourly = st_conflicts['hour_utc'].value_counts().reindex(range(24), fill_value=0)
            print(f"  {'UTC Hour':<10} | {'Conflicts':<10} | {'Volume Histogram'}")
            print("  " + "-" * 50)
            for hour in range(24):
                count = hourly[hour]
                bar = "█" * count if count > 0 else "-"
                print(f"  {hour:02d}:00 UTC   | {count:<10} | {bar}")
        print("\n")

# Run analysis using DataFrames from calculation script
print_station_analytics(df_passes, df_conflicts)
